using LAB8;

HotelList htlList = new HotelList();
htlList.AddHotel("The Den", "The Vault",20);
htlList.GetHotel(0).SetRoomsPrice(new[] { 110, 360, 44 }, new int[][] { new int[] {1,2,3,4,5,6,7}, new int[] {8,9,10,11,12,13,14,15,16}, new int[] {17,18,19,20} });
htlList.PrintHotelNames();
string Hotlename = Console.ReadLine();
Hotlename.Trim();
htlList.FindHotel(Hotlename);
htlList.AddHotel("Sierra Madre" , "The best",20);
htlList.GetHotel(1).SetRoomsPrice(new[] { 110, 360, 44 }, new int[][] { new int[] {1,2,3,4,5,6,7}, new int[] {8,9,10,11,12,13,14,15,16}, new int[] {17,18,19,20} });
htlList.RemoveHotel(0);
htlList.PrintHotelNames();
Client client = new Client("John", "Doe");
htlList.GetHotel(0).AddClient(client);
Client client2 = new Client("John", "Bill");
htlList.GetHotel(0).AddClient(client2);
htlList.GetHotel(0).PrintClientList();
htlList.GetHotel(0).ChangeClientData(1, "John", "D");
htlList.GetHotel(0).SortClientList(1);
htlList.GetHotel(0).PrintClientList();
htlList.GetHotel(0).SortClientList(2);
htlList.GetHotel(0).PrintClientList();
htlList.GetHotel(0).RemoveClient(client);
htlList.GetHotel(0).AddOrder(client2, 13, DateTime.Now, TimeSpan.FromDays(5));
htlList.GetHotel(0).AddOrder(client2, 12, DateTime.Now, TimeSpan.FromDays(15));
var order = new Order(client2, DateTime.Now , TimeSpan.FromDays(5));
htlList.GetHotel(0).ChangeOrder(client2, 13, DateTime.Now, TimeSpan.FromDays(10));
order = new Order(client2, DateTime.Now, TimeSpan.FromDays(10));
htlList.GetHotel(0).RemoveOrder(order);
htlList.GetHotel(0).PrintEmptyRooms(DateTime.Now);
htlList.GetHotel(0).PrintOrderAmount();
htlList.GetHotel(0).PrintClientList();
htlList.GetHotel(0).PrintAllOrders();
